version: '2'

services:
  postfix:
    image: postfix
    container_name: postfix
    environment:
      - MTP_HOST=mail.example.com
      - MTP_USERS=test@mail.example.com:test
    ports:
      - "25:25"
