version: '2'

services:
  postfix:
    image: postfix
    container_name: postfix
    environment:
      - MTA_HOST=mail.example.com
      - MTA_USERS=test@mail.example.com:test
    ports:
      - "25:25"
