version: '2'

services:
  postfix:
    image: postfix
    container_name: postfix
    environment:
      - MTA_DOMAIN=example.com
      - MTA_HOST=mail.example.com
      - MTA_USERS=test@mail.example.com:test
    volumes:
      - dkim_keys:/etc/opendkim/keys
    ports:
      - "25:25"
    restart: always
